---
title: "07_MADS_box"
author: "Julin Maloof"
date: "`r Sys.Date()`"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


Where are the MADS box genes relative to the LFY1 and LFY2 in the various networks that I have built?

```{r}
CrLFY1 <- "Ceric.33G031700"

CrLFY2 <- "Ceric.18G076300"
```


```{r}
MADS <- read_csv("../input/CrMADS_Carr.csv") # These are from Carr thesis
```
## WGCNA

### gametophyte samples
```{r}
load("../output/WGCNA_gametophyte_all.Rdata")
gmodule.assignment <- module.assignment %>%
  mutate(geneID = str_remove(geneID, "\\.v2.*"))
```

```{r}
MADS.gmodules <- gmodule.assignment %>% semi_join(MADS)
```

```{r}
table(MADS.gmodules$module)
```

```{r}
gmodule.assignment %>% filter(str_detect(geneID, CrLFY1))
```

```{r}
gmodule.assignment %>% filter(str_detect(geneID, CrLFY2))
```

```{r}
MADS.gmodules %>% filter(str_detect(module, "pink|turquoise"))
```

Test for sig. enrichment


```{r}
lfy1.gmodule <- gmodule.assignment %>% filter(str_detect(geneID, CrLFY1)) %>% pull(module)

lfy2.gmodule <- gmodule.assignment %>% filter(str_detect(geneID, CrLFY2)) %>% pull(module)

gfisherinput <- gmodule.assignment %>%
  mutate(lfy1.module = str_detect(module, lfy1.gmodule),
         lfy2.module = str_detect(module, lfy2.gmodule),
         mads.gene=geneID %in% MADS$geneID,
         mutate(across(-geneID, factor)))
```


```{r}
fisher.test(gfisherinput$lfy1.module, gfisherinput$mads.gene)
```
```{r}
fisher.test(gfisherinput$lfy2.module, gfisherinput$mads.gene)
```

### Sporophyte samples
```{r}
load("../output/WGCNA_sporophyte_all.Rdata")
smodule.assignment <- module.assignment %>%
  mutate(geneID = str_remove(geneID, "\\.v2.*"))
```

```{r}
MADS.smodules <- smodule.assignment %>% semi_join(MADS)
```
```{r}
table(MADS.smodules$module)
```



```{r}
smodule.assignment %>% filter(str_detect(geneID, CrLFY1))
```
```{r}
smodule.assignment %>% filter(str_detect(geneID, CrLFY2))
```
```{r}
MADS.smodules %>% filter(str_detect(module, "blue"))
```


## TGCN Gametophyte

### LFY1 Cutoff 6

```{r}
read_csv("../output/TGCN_LFY1_gam/results/LFY1_gam_c6_TGCN.csv") %>% 
  mutate(geneID = str_remove(genes, "\\.[0-9]$")) %>%
  semi_join(MADS)
```

### LFY2 Cutoff 5

```{r}
read_csv("../output/TGCN_LFY2_gam/results/LFY2_gam_c5_TGCN.csv") %>%
  mutate(geneID = str_remove(genes, "\\.[0-9]$")) %>%
  semi_join(MADS)
```

## TGCN Sporophyte

### LFY1 Cutoff 6

```{r}
read_csv("../output/TGCN_LFY1_sp/results/LFY1_sp_c6_TGCN.csv") %>% 
  mutate(geneID = str_remove(genes, "\\.[0-9]$")) %>%
  semi_join(MADS)
```

### LFY2 Cutoff 5

```{r}
read_csv("../output/TGCN_LFY2_sp/results/LFY2_sp_c5_TGCN.csv") %>%
  mutate(geneID = str_remove(genes, "\\.[0-9]$")) %>%
  semi_join(MADS)
```
