---
title: "09_MR_intersection_with_gametophyte_sexDE"
output: html_notebook
---

Create a mutual rank network and intersect that with male vs hermaphrodite DE genes.

```{r}
library(tidyverse)
```
```{r}
CrLFY1 <- "Ceric.33G031700.1" 

CrLFY2 <- "Ceric.18G076300.1"
```


```{r}
sample.description <- read.csv("../output/sample.description.gametophyte.no4.5DAG.csv")
```


load read counts. These should be log2 cpm or Voom transformed or something similar.

```{r}
lcpm <- read.csv("../output/gam_combined_log2cpm_no4.5DAG.csv.gz", row.names = 1, check.names = FALSE) 
rownames(lcpm) <- str_remove(rownames(lcpm), fixed(".v2"))
head(lcpm)
dim(lcpm)
```

load DEG list for male vs hermaphrodite
```{r}
deg <- read_csv("../../McConnell_Samples/output/DEG_ALL_WT_male_v_herm.csv.gz") %>%
  slice_sample(n=nrow(.))
deg
```

Filter to keep the genes in the deg set
```{r}
lcpm <- lcpm[deg$geneID,]
```

correlation matrix
```{r}
m.cor <- cor(t(lcpm))
diag(m.cor) <- 0
```

rank matrix
```{r}
mem.maxVSize(30000)
m.rank <- apply(m.cor,2,function(x) rank(-abs(x)))
```

MR matrix
```{r}
MR <- sqrt(m.rank * t(m.rank))
MR[1:10,1:10]
```
Create LFY specific subsets of these tables
```{r}
cor.lfy <- m.cor[,c(CrLFY1, CrLFY2)] %>%
  round(3) %>%
  as_tibble(rownames = "geneID") %>%
  rename(LFY1.cor = contains(CrLFY1), LFY2.cor = contains(CrLFY2))

MR.lfy <- MR[,c(CrLFY1, CrLFY2)] %>%
  as_tibble(rownames = "geneID") %>%
  rename(LFY1.MR = contains(CrLFY1), LFY2.MR = contains(CrLFY2))
```



combine them

```{r}
deg.cor <- deg %>% right_join(cor.lfy) %>% 
  left_join(MR.lfy) %>%
  mutate(LFY1.rank = rank(-abs(LFY1.cor)),
         LFY2.rank = rank(-abs(LFY2.cor))) %>%
  select(geneID:FDR, starts_with("LFY"), everything()) %>%
  mutate(FDR.lt.0.05=FDR<0.05)
```

```{r}
deg.cor
```

```{r}
write_csv(deg.cor, "../../McConnell_Samples/output/DEG_ALL_WT_male_v_herm_LFY_CORRELATIONS.csv.gz")
```

```{r}
deg.cor %>%
  ggplot(aes(x=logFC, y=LFY1.cor)) +
  geom_point(alpha=.05)
```
```{r}
deg.cor %>%
  ggplot(aes(x=logFC, y=LFY2.cor)) +
  geom_point(alpha=.1)
```
```{r}
deg.cor %>%
  ggplot(aes(x=LFY1.MR, y=logFC)) +
  geom_point(alpha=.1)
```
```{r}
deg.cor %>%
  ggplot(aes(x=LFY1.rank, y=logFC)) +
  geom_point(alpha=.1)
```

```{r}
deg.cor %>%
  ggplot(aes(x=LFY2.MR, y=logFC)) +
  geom_point(alpha=.1)
```


```{r}
deg.cor %>%
  ggplot(aes(x=LFY2.rank, y=logFC)) +
  geom_point(alpha=.1)
```

```{r}
deg.cor %>%
  arrange(LFY1.rank) %>%
  slice_tail(n=14000)
```

