---
title: "15_Compare_Atallah_McConnell"
author: "Julin Maloof"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Compare GO and DEG in the Attalah (immature) and McConnell (mature) gametophyte samples

```{r}
library(tidyverse)
library(ggVennDiagram)
library(edgeR)
```

## MDS

```{r}
mcconnell_counts <- read_csv("../../McConnell_Samples/output/counts_unfiltered_male_herm.csv.gz")
atallah_counts <- read_csv("../output/counts_unfiltered_Atallah.csv.gz")
```
```{r}
head(mcconnell_counts)
```

```{r}
head(atallah_counts)
```


```{r}
all_counts <- full_join(mcconnell_counts, atallah_counts)
all_counts[is.na(all_counts)] <- 0
```

```{r}
head(all_counts)
```


```{r}
sample_description <- tibble(sample_ID = colnames(all_counts[-1])) %>%
  mutate(
       stage = rep(c("mature", "immature"), each = 6),
       trt = str_extract(sample_ID, "male|herm|ctrl|antheridogen"),
       group = str_c(stage, trt)
  )
sample_description
```

remove low read genes:

```{r}
nrow(all_counts)
all_counts <- all_counts[rowSums(all_counts[,-1] > 5) >= 3,]
nrow(all_counts)
```

```{r}
counts_matrix <- all_counts %>% select(-gene_ID) %>% as.matrix()
rownames(counts_matrix) <- all_counts$gene_ID

dge.data <- DGEList(counts=counts_matrix, 
                    group=sample_description$group)
dim(dge.data) 
dge.data <- calcNormFactors(dge.data, method = "TMM")
dge.data$samples # look at the normalization factors
```

## MAKE AN MDS

```{r}
mdsvals <- plotMDS(dge.data, plot = FALSE) # get the MDS values for plotting
```


```{r}
mdsvals2 <- tibble(MDS1=mdsvals$x, MDS2=mdsvals$y, sample_ID=rownames(dge.data$samples)) %>%
  inner_join(sample_description) %>%
  mutate(sample = ifelse(str_detect(trt, "ctrl|herm"), "ctrl / hermaphrodite", "antheridogen / male"))

var.explained <- mdsvals$var.explained[1:2] %>% magrittr::multiply_by(100) %>% round(1) %>% str_c(" (", ., "%)")


mdsvals2 %>%  ggplot(aes(x=MDS1, y=MDS2, color=stage, shape = sample)) +
  #scale_color_brewer(type="qual", palette = 1) +
  theme_bw() +
  geom_point(size=3) +
  labs(x = str_c("Dimension 1", var.explained[1]),  y = str_c("Dimension 2", var.explained[2]))

ggsave("../output/McConnell_Atallah_MDS.png")

ggsave("../output/McConnell_Atallah_MDS.pdf")

```

## DEGs

```{r}
atallah_deg <- read_csv("../output/DEG_ALL_Atallah.csv.gz")
# note "up" is ctrl (no antheridogen)

mcconnell_deg <- read_csv("../../McConnell_Samples/output/DEG_ALL_WT_male_v_herm.csv.gz")
# note "up" is hermaphrodites
```

Venn Diagram
```{r}
venn_list <- list(
  McConnell_hermaphrodite = mcconnell_deg %>% filter(FDR < 0.01, logFC > 0) %>% pull(geneID),
  Atallah_ctrl = atallah_deg %>% filter(FDR < 0.01, logFC > 0) %>% pull(geneID),
  Atallah_antheridogen = atallah_deg %>% filter(FDR < 0.01, logFC < 0) %>% pull(geneID),
  McConnell_male = mcconnell_deg %>% filter(FDR < 0.01, logFC < 0) %>% pull(geneID)
)

v_data <- process_data(Venn(venn_list))


category_names = c("McConnell\nhermaphrodite", "Atallah\ncontrol", "Atallah\nantheridogen", "McConnell\nmale")

ggplot() +
  # 1. region count layer
  geom_polygon(aes(X, Y, fill = count, group = id), 
               data = venn_regionedge(v_data)) +
  # 2. set edge layer
  geom_path(aes(X, Y, color = id, group = id), 
            data = venn_setedge(v_data), 
            show.legend = FALSE) +
  # 3. set label layer
  geom_text(aes(X, Y*1.02, label = category_names), 
            data = venn_setlabel(v_data)) +
  # 4. region label layer
  geom_label(aes(X, Y, label = count), 
             fill = "grey90",
             data = venn_regionlabel(v_data)) +
  coord_equal() +
  theme_void() +
  scale_x_continuous(expand = expansion(mult = .2)) 

ggsave("../Atallah_McConnell_Venn.pdf")
ggsave("../Atallah_McConnell_Venn.png")
```
```{r}
#males and antheridogen
mcconnell_deg %>% mutate(up_male = FDR < 0.01 & logFC<0) %>%
  select(geneID, up_male) %>%
  full_join(atallah_deg, by = "geneID") %>%
  mutate(up_antheridogen = FDR < 0.01 & logFC<0) %>%
  fisher.test(x=.$up_male, y = .$up_antheridogen)
```
```{r}
#hermaphrodites and ctrl
mcconnell_deg %>% mutate(up_herm = FDR < 0.01 & logFC>0) %>%
  select(geneID, up_herm) %>%
  full_join(atallah_deg, by = "geneID") %>%
  mutate(up_ctrl = FDR < 0.01 & logFC>0) %>%
  fisher.test(x=.$up_herm, y = .$up_ctrl)
```

## GOs

```{r}
atallah_go_antheridogen <- read_csv("../output/GO_up_antheridogen_Atallah.csv") #empty
atallah_go_control <- read_csv("../output/GO_down_antheridogen_Atallah.csv")
mcconnell_go_male <- read_csv("../../McConnell_Samples/output/GO_down_WT_male_v_herm.csv") # 1 row
mcconnell_go_hermaphrodites <- read_csv("../../McConnell_Samples/output/GO_up_WT_male_v_herm.csv")
```

```{r}
atallah_go_control <- atallah_go_control %>%
  mutate(enrichment=numDEInCat/numInCat) %>%
  select(term, enrichment, FDR)

mcconnell_go_hermaphrodites <- mcconnell_go_hermaphrodites %>%
  mutate(enrichment=numDEInCat/numInCat) %>%
  select(term, enrichment, FDR)

mcconnell_go_male <- mcconnell_go_male %>%
  mutate(enrichment=numDEInCat/numInCat) %>%
  select(term, enrichment, FDR)

ctrl_herm_combined <- bind_rows(Atallah = atallah_go_control, McConnell = mcconnell_go_hermaphrodites,.id="data_set")

all_combined <- bind_rows(Atallah_hermaphrodite = atallah_go_control, McConnell_hermaphrodite = mcconnell_go_hermaphrodites, McConnell_male = mcconnell_go_male, .id="data_set")
```

```{r}
ctrl_herm_combined %>%
  group_by(term) %>%
  mutate(enrich_max = max(enrichment, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(term=fct_reorder(term, enrich_max, .desc = FALSE)) %>%
  ggplot(aes(x=data_set, y = term, size = enrichment, color = -log10(FDR))) +
  geom_point()

ggsave("../output/Atallah_McConnell_GO_herm_ctrl.pdf")
ggsave("../output/Atallah_McConnell_GO_herm_ctrl.png")
```

```{r, fig.height=6}
all_combined %>%
  group_by(term) %>%
  separate(data_set, into = c("Study", "Sex")) %>%
  mutate(Sex = ifelse(Sex == "male", "antheridogen / male", Sex),
         enrich_max = max(enrichment, na.rm = TRUE),
         FDR_min = min(FDR, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(term=fct_reorder(term, enrich_max, .desc = FALSE)) %>%
  ggplot(aes(x=Study, y = term, size = enrichment, color = -log10(FDR))) +
  geom_point() +
  facet_wrap(~Sex, ncol=1, scale = "free_y", space = "free_y") +
  theme(axis.title.x = element_blank()) +  
  scale_color_gradient(transform = "log10", high = "#132B43", low = "#86E1F7")

ggsave("../output/Atallah_McConnell_GO_all.pdf")
ggsave("../output/Atallah_McConnell_GO_all.png")
```


## output combined list

```{r}
combined <- mcconnell_deg %>%
  select(geneID:FDR) %>%
  full_join(atallah_deg, by = "geneID", suffix = c(".mcconnell", ".atallah")) %>%
  mutate(up.male.both = logFC.mcconnell < 0 & logFC.atallah < 0 & FDR.mcconnell < 0.01 & FDR.atallah < 0.01,
         up.hermaphrodite.both = logFC.mcconnell > 0 & logFC.atallah > 0 & FDR.mcconnell < 0.01 & FDR.atallah < 0.01,
         up.male.mcconnell.only  = logFC.mcconnell < 0 & FDR.mcconnell < 0.01 & (is.na(FDR.atallah) | FDR.atallah >= 0.01),
         up.male.atallah = logFC.atallah < 0 & (is.na(FDR.mcconnell) | FDR.mcconnell >= 0.01) & FDR.atallah < 0.01,
         up.herm.mcconnell.only = logFC.mcconnell > 0 & FDR.mcconnell < 0.01 & (is.na(FDR.atallah) | FDR.atallah >= 0.01),
         up.herm.attallah.only = logFC.atallah > 0 & (is.na(FDR.mcconnell) | FDR.mcconnell >= 0.01) & FDR.atallah < 0.01,
  ) %>%
  select(geneID, starts_with("up"), everything()) %>%
  arrange(FDR.mcconnell)

combined

write_csv(combined, "../output/Atallah_McConnell_DEG_combined.csv.gz")
```

