---
title: "16_Compare_Atallah_McConnell_Marchant"
author: "Julin Maloof"
date: "`r Sys.Date()`"
output: html_document
---

Comparing total expressed genes in Atallah, McConnell, and Marchant data sets.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggVennDiagram)
```

## load data

### Atallah and McConnell data

Because the Marchant data is pooled into a single sample I will do the same here to make things more comparable.
```{r}
atallah <- read_csv("../output/counts_unfiltered_Atallah.csv.gz") %>%
  rowwise() %>%
  mutate(sum_count = sum(c_across(-gene_ID))) %>%
  ungroup() %>%
  select(gene_ID, sum_count)

mcconnell <- read_csv("../../McConnell_Samples/output/counts_unfiltered_male_herm.csv.gz") %>%
    rowwise() %>%
  mutate(sum_count = sum(c_across(-gene_ID))) %>%
  ungroup() %>%
  select(gene_ID, sum_count)
```

### Marchant

```{r}
marchant <- read_delim("../output/ht-seq-counts_ncbi.csv.gz") %>%
  select(gene_ID, Marchant_mature=SRR12605697, Marchant_immature=SRR12605696) 
```

Total counts
```{r}
atallah$sum_count %>% sum()

mcconnell$sum_count %>% sum()

marchant$Marchant_immature %>% sum()

marchant$Marchant_mature %>% sum()
```



Venn Diagram of genes with > 5 counts (raw)

```{r}
venn_list5 = list(McConnell = 
                    {mcconnell %>% filter(sum_count > 5) %>% pull(gene_ID)},
                 Atallah=
                   {atallah %>% filter(sum_count > 5) %>% pull(gene_ID)},
                 Marchant_immature =
                   { marchant %>% filter(Marchant_immature > 5) %>% pull(gene_ID)},
                 Marchant_mature =
                   { marchant %>% filter(Marchant_mature > 5) %>% pull(gene_ID)})

v_data5 <- process_data(Venn(venn_list5))

category_names = c("McConnell", "Atallah", "Marchant\nimmature", "Marchant\nmature")

ggplot() +
  # 1. region count layer
  geom_polygon(aes(X, Y, fill = count, group = id), 
          data = venn_regionedge(v_data5)) +
  # 2. set edge layer
  geom_path(aes(X, Y, color = id, group = id), 
          data = venn_setedge(v_data5), 
          show.legend = FALSE) +
  # 3. set label layer
  geom_text(aes(X, Y*1.02, label = category_names), 
               data = venn_setlabel(v_data5)) +
  # 4. region label layer
  geom_label(aes(X, Y, label = str_c(count, "\n(", round(100*count/sum(count),1), "%)")), 
             fill = "grey90",
                data = venn_regionlabel(v_data5)) +
  coord_equal() +
  theme_void() +
    scale_x_continuous(expand = expansion(mult = .2)) 
```

## cpm

```{r}
mcconnell_cpm <- mcconnell %>%
  mutate(sum_count = 1e6 * sum_count/sum(sum_count))

atallah_cpm <- atallah %>%
  mutate(sum_count = 1e6 * sum_count/sum(sum_count))

marchant_cpm <- marchant %>%
  mutate(across(-gene_ID, \(x) 1e6 * x/sum(x)))
```




Venn Diagram of genes with > 5 counts (raw)

```{r}
venn_listcpm1 = list(McConnell = 
                    {mcconnell_cpm %>% filter(sum_count > 1) %>% pull(gene_ID)},
                 Atallah=
                   {atallah_cpm %>% filter(sum_count > 1) %>% pull(gene_ID)},
                 Marchant_immature =
                   { marchant %>% filter(Marchant_immature > 1) %>% pull(gene_ID)},
                 Marchant_mature_cpm =
                   { marchant %>% filter(Marchant_mature > 1) %>% pull(gene_ID)})

v_datacpm1 <- process_data(Venn(venn_listcpm1))

category_names = c("McConnell", "Atallah", "Marchant\nimmature", "Marchant\nmature")

ggplot() +
  # 1. region count layer
  geom_polygon(aes(X, Y, fill = count, group = id), 
          data = venn_regionedge(v_datacpm1)) +
  # 2. set edge layer
  geom_path(aes(X, Y, color = id, group = id), 
          data = venn_setedge(v_datacpm1), 
          show.legend = FALSE) +
  # 3. set label layer
  geom_text(aes(X, Y*1.02, label = category_names), 
               data = venn_setlabel(v_datacpm1)) +
  # 4. region label layer
  geom_label(aes(X, Y, label = str_c(count, "\n(", round(100*count/sum(count),1), "%)")), 
             fill = "grey90",
                data = venn_regionlabel(v_datacpm1)) +
  coord_equal() +
  theme_void() +
    scale_x_continuous(expand = expansion(mult = .2)) 
```