---
title: "03_EdgeR"
author: "Julin Maloof"
date: "2024-12-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(edgeR)
```

```{r}
counts.data <- read_csv("../output/ht-seq-counts-combined.csv.gz")
head(counts.data)
```

```{r}
counts.data <- counts.data %>%
  rename_with(.fn = ~ str_remove(.x, "RESUB-")) %>%
  rename_with(.fn = ~ str_replace(.x, "(male|mature)-", "\\1_"))
```


```{r}
sample.description <- tibble(sample=colnames(counts.data)[-1]) %>%
  mutate(gt=str_extract(sample, "^[a-zA-Z0-9]*"),
         base_gt=str_remove(gt, "[0-9]+"),
         base_gt=str_replace(base_gt, "BA", "CrLFY1-OX"),
         base_gt=str_replace(base_gt, "B(D|F)", "CrLFY2-OX"),
         tissue=str_remove(sample, "^[a-zA-Z0-9]*-")) %>%
  separate(tissue, into=c("tissue", "rep"), sep = "-", fill="right", extra="merge") %>%
  mutate( group=str_c(base_gt, "-", tissue))

sample.description
```

```{r}
counts.data %>% filter(!str_detect(gene_ID, "Ceric"))
```

```{r}
counts.data <- counts.data %>% filter(str_detect(gene_ID, "Ceric"))
```

remove low read genes:

```{r}
counts.data <- counts.data[rowSums(counts.data[,-1] > 5) >= 3,]
```

```{r}
counts.matrix <- counts.data %>% select(-gene_ID) %>% as.matrix()
rownames(counts.matrix) <- counts.data$gene_ID

dge.data <- DGEList(counts=counts.matrix, 
                    group=sample.description$group)
dim(dge.data) 
dge.data <- calcNormFactors(dge.data, method = "TMM")
dge.data$samples # look at the normalization factors
```

NOTE THAT THE S5 SAMPLES HAVE MUCH LOWER NORM.FACTORS THAN EVERYTHING ELSE.  WE MAY WANT TO HANDLE THESE DIFFERNETLY, DEPENDING ON WHAT THESE SAMPLES ARE

## MAKE AN MDS

```{r}
mdsvals <- plotMDS(dge.data, plot = FALSE) # get the MDS values for plotting
```


```{r}
mdsvals2 <- tibble(x=mdsvals$x, y=mdsvals$y, sample=rownames(dge.data$samples)) %>%
  inner_join(sample.description)


mdsvals2 %>%  ggplot(aes(x=x, y=y, color=tissue, shape=base_gt)) +
  scale_color_brewer(type="qual", palette = 3) +
  theme_bw() +
  geom_point(size=3) 
```

### S5 only

```{r}
dge.data.S5 <-dge.data[,str_detect(dge.data$samples$group, "S5")]
dim(dge.data.S5) 
dge.data.S5 <- calcNormFactors(dge.data.S5, method = "TMM")

MDSval.S5 <- plotMDS(dge.data.S5, plot = FALSE) # get the MDS values for plotting
tibble(x=MDSval.S5$x, y=MDSval.S5$y, sample=rownames(dge.data.S5$samples)) %>%
  inner_join(sample.description) %>% 
  ggplot(aes(x=x, y=y, shape=base_gt)) +
  theme_bw() +
  geom_point(size=3) +
  ggtitle("S5")
```

### WYS only

```{r}
dge.data.WYS <-dge.data[,str_detect(dge.data$samples$group, "WYS")]
dim(dge.data.WYS) 
dge.data.WYS <- calcNormFactors(dge.data.WYS, method = "TMM")

MDSval.WYS <- plotMDS(dge.data.WYS, plot = FALSE) # get the MDS values for plotting
tibble(x=MDSval.WYS$x, y=MDSval.WYS$y, sample=rownames(dge.data.WYS$samples)) %>%
  inner_join(sample.description) %>% 
  ggplot(aes(x=x, y=y, shape=base_gt)) +
  theme_bw() +
  geom_point(size=3) +
  ggtitle("WYS")
```

one WT sample strangely placed

### gam only

```{r}
dge.data.gam <- dge.data[,str_detect(dge.data$samples$group, "gam|herm")]
dim(dge.data.gam) 
dge.data.gam <- calcNormFactors(dge.data.gam, method = "TMM")

MDSval.gam <- plotMDS(dge.data.gam, plot = FALSE) # get the MDS values for plotting
tibble(x=MDSval.gam$x, y=MDSval.gam$y, sample=rownames(dge.data.gam$samples)) %>%
  inner_join(sample.description) %>% 
  ggplot(aes(x=x, y=y, color=tissue, shape=base_gt)) +
  scale_color_brewer(type="qual", palette = 3) +
  theme_bw() +
  geom_point(size=3) +
  ggtitle("gam")
```
## Check LFY Levels

CrLFY1: Ceric.33G031700

CrLFY2: Ceric.18G076300

### LFY1:

