---
title: "05_GO_WGCNA"
output: html_notebook
---

```{r}
library(tidyverse)
library(topGO)
#library(clusterProfiler)
```

```{r}
load("../output/WGCNA_allSamples.Rdata")
```


```{r}
GOs <- read_delim("../input/Crichardii_676_v2.1.annotation_info.txt")
head(GOs)
tail(GOs)
```

how will do the gene IDs match up?
```{r}
moduleGOs <- module.assignment %>%
  mutate(geneID2 = str_remove(geneID, fixed(".v2"))) %>%
  inner_join(GOs, by = c("geneID2" = "transcriptName")) %>%
  select(geneID, module, GO)

dim(module.assignment)
dim(moduleGOs)
head(moduleGOs)
```
Great.  All genes in module.assignments are retained after the join

Create a gene2GO list needed by topGO:

```{r}
gene2GO.list <- moduleGOs %>% 
  rowwise() %>%
  mutate(GOlist = str_split(GO, pattern = " ")) %>%
  ungroup() %>%
  mutate(GOlist = set_names(GOlist, geneID)) %>%
  pull(GOlist)
```

Test on one module:

```{r}
magenta <- module.assignment %>%
  mutate(magenta = as.numeric(module == "magenta")) %>% 
  pull(magenta, name = geneID) %>% as.factor()
```

```{r}
go.data.magenta <- new("topGOdata", ontology = "BP", description = "magenta", allGenes = magenta, annot = annFUN.gene2GO, gene2GO = gene2GO.list)
result.magenta <- runTest(go.data.magenta, algorithm = "weight01", statistic = "fisher")
```
```{r}
GenTable(go.data.magenta, result.magenta, topNodes = sum(result.magenta@score < 0.01 )) %>%
  dplyr::rename(P_val=result1)
```

